INSERT INTO reviews.review (productId, averageReviewScore, numberOfReviews) VALUES ('123', 0.5, 2);
INSERT INTO reviews.review (productId, averageReviewScore, numberOfReviews) VALUES ('321', 0.7, 1);
INSERT INTO reviews.review (productId, averageReviewScore, numberOfReviews) VALUES ('136', 0.45, 5);
INSERT INTO reviews.review (productId, averageReviewScore, numberOfReviews) VALUES ('IC2129', 0.456, 57);
INSERT INTO reviews.review (productId, averageReviewScore, numberOfReviews) VALUES ('HP3205', 0.99, 2567);
INSERT INTO reviews.review (productId, averageReviewScore, numberOfReviews) VALUES ('IK8326', 0.89, 9909);